### PR TITLE
Added new steps, JSON Pointer {path} is any integer/float

### PR DESCRIPTION
**Pull request by lcosmin**
I've added two new steps,  `JSON Pointer "{path}" is any integer` and `JSON Pointer "{path}" is any float` to test if a json pointer is an integer/float (any value).

### CODE REVIEW

**Comment by dsuch** [comment]
One thing @lcosmin - can it use ```isinstance``` rather than ```type``` directly - who knows how the code will be extended with time and using isinstance will guard us against any future quirks.

Thanks a lot, otherwise, this is good stuff, as usual!

**Comment by lcosmin** [comment]
Ok, changed it to use `isinstance`, can you take a look?  I also added a check for the `long` type of Python 2.x (forgot about that...)

**Comment by dsuch** [comment]
Sorry to pick on it but *isinstance* simply accepts a tuple of types to check.

So this could be simplified to

```python
int_types = (int, long) # Or (int,) for Python 3
isinstance(actual, int_types)
```

What do you think?

**Comment by lcosmin** [comment]
Hah! I had no idea it can check for multiple things at once :smiley:  changed!

**Pull request merged**
