### PR TITLE
This will add the (Ehhh, hidden?) option "-b" or "--behave_options" whic...

### PR DESCRIPTION
**Pull request by thomasez**
...h will add the values to behave_options from the config.ini before behave is run. I made this to support the --tags options in Behave.

Usage-example:
    apitest --behave_options="--tags=thisone" run .

### CODE REVIEW

**Comment by dsuch** [comment]
Hi @thomasez - I like the idea but the implementation should be different to make it more in line with already existing codebase.

* New CLI options go to: [zato.apitest.cli](https://github.com/zatosource/zato-apitest/blob/master/src/zato/apitest/cli.py)

* Any options CLI receives are provided to [zato.apitest.run:handle] https://github.com/zatosource/zato-apitest/blob/master/src/zato/apitest/run.py as parameters. Here *--behave-options* will be optional so it can be an empty dictionary

* Parameters on command line will override those in config.ini - I think it already works this way in your patch?

This is good stuff it's just that the implementation should be changed. Thanks.

**Comment by thomasez** [comment]
I wonder how I missed click in cli.py since I've messed around with it before..

> Parameters on command line will override those in config.ini - I think it already works this way in your patch?

Should it? Maybe have both --behave-options and --extra-behave-options? I agree with it being an override, but too lazy to want (and remember) to add the ones from config.ini 

PR coming up, one or two (override first, then another for accumulative)

**Comment by dsuch** [comment]
Hi @thomasez 

> Should it? Maybe have both --behave-options and --extra-behave-options?

Let me clarify - if both ```config.ini``` and CLI parameters provide the same thing, the latter will take precedence. But if the former has keys the latter doesn't, the result is a sum of both, not the latter.

In Python terms:

```python
>>> default_opts = {'key1':'value1', 'key2':'value2'}
>>> cli_opts = {'key2':'value22', 'key3':'value3'}

# Merge options
>>> default_opts.update(cli_opts)

>>> print(default_opts)
{'key3': 'value3', 'key2': 'value22', 'key1': 'value1'}
>>> 
```

The code look OK, I'll be merging it soon-ish. Thanks for the PR!

**Comment by thomasez** [comment]
Aha, thanks.

On the other hand, the options sent to behave is a string, not a dict as far as I can see.. And I've treated it like a string, which works.

I guess it could be possible to parse, merge and then create a string for behave to parse. And that's probably the way to do override/merge instead of a replace which I've done.

**Comment by dsuch** [comment]
Mass-closing old tickets.

**Pull request closed without merging**
